FROM golang:1.17 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/app --mod=vendor

FROM scratch

COPY --from=builder /go/bin/app /app

EXPOSE 8080

ENTRYPOINT ["/app"]
