version: "3.8"

services:
  conb20bb005_1:
    container_name: CONB20BB005_1
    image: xandertw/b20bb005-assessment3-csl7510-web:latest
    ports:
      - "8080:8080"
    depends_on:
      - conb20bb005_2
    networks:
      - b20bb005

  conb20bb005_2:
    container_name: CONB20BB005_2
    image: xandertw/b20bb005-assessment3-csl7510-db:latest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - b20bb005

volumes:
  pg_data:

networks:
  b20bb005:
    driver: bridge
