# Use Debian Buster Slim as the base image
FROM debian:buster-slim

# Install PostgreSQL and contrib package
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Switch to the postgres user
USER postgres

# Initialize the database and create a user and database
RUN /etc/init.d/postgresql start && \
    psql --command "CREATE USER b20bb005 WITH SUPERUSER PASSWORD 'toor';" && \
    createdb -O b20bb005 userdb && \
    /etc/init.d/postgresql stop

# Configure pg_hba.conf for host-based authentication
RUN echo "local all all trust" > /etc/postgresql/11/main/pg_hba.conf && \
    echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/11/main/pg_hba.conf && \
    echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/11/main/pg_hba.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Set up volumes for PostgreSQL data and logs
VOLUME ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run PostgreSQL
CMD ["/usr/lib/postgresql/11/bin/postgres", "-D", "/var/lib/postgresql/11/main", "-c", "config_file=/etc/postgresql/11/main/postgresql.conf"]
